# Generated by Django 2.1.7 on 2019-02-25 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0005_auto_20190225_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='bpub_date',
            field=models.DateField(default=datetime.datetime(1990, 1, 1, 0, 0)),
        ),
    ]
