# Generated by Django 2.1.7 on 2019-03-05 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0007_auto_20190226_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(upload_to='booktest/')),
            ],
        ),
    ]
